/*
 * ai_edge.h
 * =========
 * On-device (edge) inference for the two exported scikit-learn models.
 * No external ML library is needed — the models were compiled to plain C
 * arrays by ai/train_models.py:
 *
 *   arrival_probability : sigmoid( w0*x0 + ... + w5*x5 + b )
 *   charging_duration   : decision-tree walk over CSR-style arrays
 */
#pragma once

#include <Arduino.h>
#include <math.h>
#include "models.h"   // exported model arrays (generated by ai/train_models.py)

// ------------------------------------------------------------------ //
// Arrival probability (LogisticRegression)
// ------------------------------------------------------------------ //
// Inputs: hour of day (0..23.99), weekday (0..6), busy-rate multiplier.
inline float predictArrivalProbability(float hour, uint32_t weekday, float busyRate) {
  float rad = 2.0f * M_PI * hour / 24.0f;
  float hourSin = sinf(rad);
  float hourCos = cosf(rad);
  uint32_t wd = weekday % 7;
  float isWeekend = (wd >= 5) ? 1.0f : 0.0f;
  float isPeak = ((hour >= 6.5f && hour <= 9.5f) || (hour >= 16.0f && hour <= 19.5f)) ? 1.0f : 0.0f;

  float x[ARRIVAL_N_FEATURES] = {hourSin, hourCos, (float)wd, isWeekend, isPeak, busyRate};
  float z = ARRIVAL_BIAS;
  for (uint8_t i = 0; i < ARRIVAL_N_FEATURES; i++) z += ARRIVAL_COEF[i] * x[i];

  // numerically stable sigmoid
  return (z >= 0.0f) ? 1.0f / (1.0f + expf(-z)) : expf(z) / (1.0f + expf(z));
}

// ------------------------------------------------------------------ //
// Charging duration (DecisionTreeRegressor)
// ------------------------------------------------------------------ //
// Features in model order:
//   0 capacity_kwh, 1 soc0_pct, 2 socT_pct, 3 ambient_c, 4 current_a, 5 connector_temp_c
inline float predictChargeMinutes(float capacityKwh, float soc0, float socT,
                                  float ambientC, float currentA, float connTempC) {
  float x[DURATION_N_FEATURES] = {
      capacityKwh, soc0, socT, ambientC, currentA, connTempC};
  int32_t node = 0;
  while (DT_FEATURE[node] >= 0) {
    int16_t f = DT_FEATURE[node];
    node = (x[f] <= DT_THRESHOLD[node]) ? DT_LEFT[node] : DT_RIGHT[node];
  }
  return DT_VALUE[node];
}